version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3006

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    volumes:
      - ./images:/app/images:ro
      - ./converted:/app/converted
